/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as MainRouteImport } from './pages/_main'
import { Route as MainIndexRouteImport } from './pages/_main.index'
import { Route as MainSubmitRouteImport } from './pages/_main.submit'
import { Route as MainSettingsRouteImport } from './pages/_main.settings'
import { Route as MainSearchRouteImport } from './pages/_main.search'
import { Route as MainSavedRouteImport } from './pages/_main.saved'
import { Route as MainNotificationsRouteImport } from './pages/_main.notifications'
import { Route as MainMessagesRouteImport } from './pages/_main.messages'
import { Route as MainUUsernameRouteImport } from './pages/_main.u.$username'
import { Route as MainRCreateCommunityRouteImport } from './pages/_main.r.create-community'
import { Route as MainRCommunityIdRouteImport } from './pages/_main.r.$communityId'
import { Route as MainPostPostIdRouteImport } from './pages/_main.post.$postId'
import { Route as MainAuthCallbackRouteImport } from './pages/_main.auth.callback'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSubmitRoute = MainSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainSavedRoute = MainSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => MainRoute,
} as any)
const MainNotificationsRoute = MainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MainRoute,
} as any)
const MainMessagesRoute = MainMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MainRoute,
} as any)
const MainUUsernameRoute = MainUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => MainRoute,
} as any)
const MainRCreateCommunityRoute = MainRCreateCommunityRouteImport.update({
  id: '/r/create-community',
  path: '/r/create-community',
  getParentRoute: () => MainRoute,
} as any)
const MainRCommunityIdRoute = MainRCommunityIdRouteImport.update({
  id: '/r/$communityId',
  path: '/r/$communityId',
  getParentRoute: () => MainRoute,
} as any)
const MainPostPostIdRoute = MainPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => MainRoute,
} as any)
const MainAuthCallbackRoute = MainAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/messages': typeof MainMessagesRoute
  '/notifications': typeof MainNotificationsRoute
  '/saved': typeof MainSavedRoute
  '/search': typeof MainSearchRoute
  '/settings': typeof MainSettingsRoute
  '/submit': typeof MainSubmitRoute
  '/': typeof MainIndexRoute
  '/auth/callback': typeof MainAuthCallbackRoute
  '/post/$postId': typeof MainPostPostIdRoute
  '/r/$communityId': typeof MainRCommunityIdRoute
  '/r/create-community': typeof MainRCreateCommunityRoute
  '/u/$username': typeof MainUUsernameRoute
}
export interface FileRoutesByTo {
  '/messages': typeof MainMessagesRoute
  '/notifications': typeof MainNotificationsRoute
  '/saved': typeof MainSavedRoute
  '/search': typeof MainSearchRoute
  '/settings': typeof MainSettingsRoute
  '/submit': typeof MainSubmitRoute
  '/': typeof MainIndexRoute
  '/auth/callback': typeof MainAuthCallbackRoute
  '/post/$postId': typeof MainPostPostIdRoute
  '/r/$communityId': typeof MainRCommunityIdRoute
  '/r/create-community': typeof MainRCreateCommunityRoute
  '/u/$username': typeof MainUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/messages': typeof MainMessagesRoute
  '/_main/notifications': typeof MainNotificationsRoute
  '/_main/saved': typeof MainSavedRoute
  '/_main/search': typeof MainSearchRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/submit': typeof MainSubmitRoute
  '/_main/': typeof MainIndexRoute
  '/_main/auth/callback': typeof MainAuthCallbackRoute
  '/_main/post/$postId': typeof MainPostPostIdRoute
  '/_main/r/$communityId': typeof MainRCommunityIdRoute
  '/_main/r/create-community': typeof MainRCreateCommunityRoute
  '/_main/u/$username': typeof MainUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/messages'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/submit'
    | '/'
    | '/auth/callback'
    | '/post/$postId'
    | '/r/$communityId'
    | '/r/create-community'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/messages'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/submit'
    | '/'
    | '/auth/callback'
    | '/post/$postId'
    | '/r/$communityId'
    | '/r/create-community'
    | '/u/$username'
  id:
    | '__root__'
    | '/_main'
    | '/_main/messages'
    | '/_main/notifications'
    | '/_main/saved'
    | '/_main/search'
    | '/_main/settings'
    | '/_main/submit'
    | '/_main/'
    | '/_main/auth/callback'
    | '/_main/post/$postId'
    | '/_main/r/$communityId'
    | '/_main/r/create-community'
    | '/_main/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/submit': {
      id: '/_main/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof MainSubmitRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/saved': {
      id: '/_main/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof MainSavedRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/notifications': {
      id: '/_main/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MainNotificationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/messages': {
      id: '/_main/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MainMessagesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/u/$username': {
      id: '/_main/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof MainUUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/r/create-community': {
      id: '/_main/r/create-community'
      path: '/r/create-community'
      fullPath: '/r/create-community'
      preLoaderRoute: typeof MainRCreateCommunityRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/r/$communityId': {
      id: '/_main/r/$communityId'
      path: '/r/$communityId'
      fullPath: '/r/$communityId'
      preLoaderRoute: typeof MainRCommunityIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/post/$postId': {
      id: '/_main/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof MainPostPostIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/auth/callback': {
      id: '/_main/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof MainAuthCallbackRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainMessagesRoute: typeof MainMessagesRoute
  MainNotificationsRoute: typeof MainNotificationsRoute
  MainSavedRoute: typeof MainSavedRoute
  MainSearchRoute: typeof MainSearchRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainSubmitRoute: typeof MainSubmitRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAuthCallbackRoute: typeof MainAuthCallbackRoute
  MainPostPostIdRoute: typeof MainPostPostIdRoute
  MainRCommunityIdRoute: typeof MainRCommunityIdRoute
  MainRCreateCommunityRoute: typeof MainRCreateCommunityRoute
  MainUUsernameRoute: typeof MainUUsernameRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainMessagesRoute: MainMessagesRoute,
  MainNotificationsRoute: MainNotificationsRoute,
  MainSavedRoute: MainSavedRoute,
  MainSearchRoute: MainSearchRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainSubmitRoute: MainSubmitRoute,
  MainIndexRoute: MainIndexRoute,
  MainAuthCallbackRoute: MainAuthCallbackRoute,
  MainPostPostIdRoute: MainPostPostIdRoute,
  MainRCommunityIdRoute: MainRCommunityIdRoute,
  MainRCreateCommunityRoute: MainRCreateCommunityRoute,
  MainUUsernameRoute: MainUUsernameRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
